DROP SCHEMA IF EXISTS lana_dog_walking;
CREATE SCHEMA lana_dog_walking;
USE lana_dog_walking;
CREATE TABLE CLIENT (
  CLIENT_ID INT PRIMARY KEY,
  FIRST_NAME VARCHAR (25),
  LAST_NAME VARCHAR (25),
  PHONE_NUMBER VARCHAR (20),
  EMAIL VARCHAR (50),
  ADDRESS VARCHAR (100),
  PREFERRED_CONTACT_METHOD VARCHAR (50) 
  );
CREATE TABLE DOG (
  DOG_ID INT PRIMARY KEY,
  CLIENT_ID INT,
  DOG_NAME VARCHAR (50),
  BREED VARCHAR (50),
  SEX VARCHAR (10),
  COLOR_MARKINGS VARCHAR (100), 
  DOB DATE,
  MICHROCHIPPED BOOLEAN,
  NOTES VARCHAR (255), 
  FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT(CLIENT_ID) 
  );
CREATE TABLE APPOINMENT (
  APPOINTMENT_ID INT PRIMARY KEY,
  DOG_ID INT,
  DATE DATE,
  START_TIME TIME,
  DURATION INT,
  FREQUENCY VARCHAR (50),
  FEE DECIMAL (10,2),
  FOREIGN KEY (DOG_ID) REFERENCES DOG (DOG_ID)
  );
CREATE TABLE EMERGENCY_CONTACT (
  EMERGENCYCONTACT_ID INT PRIMARY KEY,
  CLIENT_ID INT,
  CONTACT_NAME VARCHAR (50),
  CONTACT_PHONE VARCHAR (20),
  FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID)
  );
CREATE TABLE WALKING_SPECIFICS (
  DOG_ID INT PRIMARY KEY,
  CLIENT_ID INT,
  ENERGY_LEVEL VARCHAR (50),
  TEMPERAMENT_NOTES VARCHAR (200),
  ESCAPE_RISK BOOLEAN,
  HEAT_SENSITIVITY BOOLEAN,
  WAKING_NOTES VARCHAR (255),
  FOREIGN KEY (DOG_ID) REFERENCES DOG (DOG_ID),
  FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID)
  );
  